apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ecomm-ui
  template:
    metadata:
      labels:
        app: ecomm-ui
    spec:
      containers:
      - image: lsimity/ecomm:latest
        name: ecomm-ui
        ports:
        - containerPort: 8001